# Generated by Django 5.2.8 on 2025-12-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
