# Generated by Django 5.2.8 on 2025-12-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listas", "0002_item_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="list",
            field=models.TextField(default=""),
        ),
    ]
