# Generated by Django 5.2.8 on 2025-12-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listas", "0004_alter_item_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="teste3",
            field=models.TextField(default=""),
        ),
    ]
