# Generated by Django 5.2.8 on 2025-12-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listas", "0005_item_teste3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="teste3",
        ),
    ]
