# Generated by Django 5.2.8 on 2025-12-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listas", "0006_remove_item_teste3"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["id"]},
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("list", "text")},
        ),
    ]
