# Generated by Django 5.2.8 on 2025-12-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listas", "0007_alter_item_options_alter_item_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={},
        ),
    ]
