# Generated by Django 5.2.8 on 2025-12-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listas", "0008_alter_item_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("id",)},
        ),
    ]
